# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CalculateS2P\Main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RL_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.RL_Label.setFont(font)
        self.RL_Label.setObjectName("RL_Label")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.RL_Label)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.RL_Table = QtWidgets.QTableWidget(self.RL_Label)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.RL_Table.setFont(font)
        self.RL_Table.setObjectName("RL_Table")
        self.RL_Table.setColumnCount(0)
        self.RL_Table.setRowCount(0)
        self.RL_Table.horizontalHeader().setDefaultSectionSize(94)
        self.RL_Table.horizontalHeader().setMinimumSectionSize(20)
        self.RL_Table.verticalHeader().setDefaultSectionSize(25)
        self.RL_Table.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_12.addWidget(self.RL_Table)
        self.verticalLayout.addWidget(self.RL_Label)
        self.MaxIL_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.MaxIL_Label.setFont(font)
        self.MaxIL_Label.setObjectName("MaxIL_Label")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.MaxIL_Label)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MaxIL_Table = QtWidgets.QTableWidget(self.MaxIL_Label)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(False)
        font.setWeight(50)
        self.MaxIL_Table.setFont(font)
        self.MaxIL_Table.setAutoScrollMargin(16)
        self.MaxIL_Table.setRowCount(0)
        self.MaxIL_Table.setColumnCount(0)
        self.MaxIL_Table.setObjectName("MaxIL_Table")
        self.MaxIL_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.MaxIL_Table.horizontalHeader().setDefaultSectionSize(94)
        self.MaxIL_Table.horizontalHeader().setMinimumSectionSize(20)
        self.MaxIL_Table.verticalHeader().setDefaultSectionSize(25)
        self.MaxIL_Table.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_4.addWidget(self.MaxIL_Table)
        self.verticalLayout.addWidget(self.MaxIL_Label)
        self.Ripple_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.Ripple_Label.setFont(font)
        self.Ripple_Label.setObjectName("Ripple_Label")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Ripple_Label)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Ripple_Table = QtWidgets.QTableWidget(self.Ripple_Label)
        self.Ripple_Table.setObjectName("Ripple_Table")
        self.Ripple_Table.setColumnCount(0)
        self.Ripple_Table.setRowCount(0)
        self.verticalLayout_13.addWidget(self.Ripple_Table)
        self.verticalLayout.addWidget(self.Ripple_Label)
        self.AvgIL_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.AvgIL_Label.setFont(font)
        self.AvgIL_Label.setObjectName("AvgIL_Label")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.AvgIL_Label)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.AvgIL_Table = QtWidgets.QTableWidget(self.AvgIL_Label)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.AvgIL_Table.setFont(font)
        self.AvgIL_Table.setRowCount(0)
        self.AvgIL_Table.setObjectName("AvgIL_Table")
        self.AvgIL_Table.setColumnCount(0)
        self.AvgIL_Table.horizontalHeader().setDefaultSectionSize(94)
        self.AvgIL_Table.horizontalHeader().setMinimumSectionSize(20)
        self.AvgIL_Table.verticalHeader().setDefaultSectionSize(25)
        self.AvgIL_Table.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_6.addWidget(self.AvgIL_Table)
        self.verticalLayout.addWidget(self.AvgIL_Label)
        self.Att_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.Att_Label.setFont(font)
        self.Att_Label.setObjectName("Att_Label")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Att_Label)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Att_Table = QtWidgets.QTableWidget(self.Att_Label)
        font = QtGui.QFont()
        font.setFamily("等线")
        self.Att_Table.setFont(font)
        self.Att_Table.setRowCount(0)
        self.Att_Table.setObjectName("Att_Table")
        self.Att_Table.setColumnCount(0)
        self.Att_Table.horizontalHeader().setDefaultSectionSize(94)
        self.Att_Table.horizontalHeader().setMinimumSectionSize(20)
        self.Att_Table.verticalHeader().setDefaultSectionSize(25)
        self.Att_Table.verticalHeader().setMinimumSectionSize(25)
        self.verticalLayout_5.addWidget(self.Att_Table)
        self.verticalLayout.addWidget(self.Att_Label)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Menu_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.Menu_Label.setFont(font)
        self.Menu_Label.setObjectName("Menu_Label")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Menu_Label)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Marker_Label = QtWidgets.QGroupBox(self.Menu_Label)
        self.Marker_Label.setObjectName("Marker_Label")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Marker_Label)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.AddButton = QtWidgets.QPushButton(self.Marker_Label)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout_9.addWidget(self.AddButton)
        self.DeleteButton = QtWidgets.QPushButton(self.Marker_Label)
        self.DeleteButton.setObjectName("DeleteButton")
        self.verticalLayout_9.addWidget(self.DeleteButton)
        self.HelpButton = QtWidgets.QPushButton(self.Marker_Label)
        self.HelpButton.setObjectName("HelpButton")
        self.verticalLayout_9.addWidget(self.HelpButton)
        self.verticalLayout_8.addWidget(self.Marker_Label)
        self.Temp_Label = QtWidgets.QGroupBox(self.Menu_Label)
        self.Temp_Label.setObjectName("Temp_Label")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Temp_Label)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ValueLabel = QtWidgets.QGroupBox(self.Temp_Label)
        self.ValueLabel.setObjectName("ValueLabel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.ValueLabel)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.ValueEdit = QtWidgets.QLineEdit(self.ValueLabel)
        self.ValueEdit.setObjectName("ValueEdit")
        self.verticalLayout_11.addWidget(self.ValueEdit)
        self.verticalLayout_10.addWidget(self.ValueLabel)
        self.LowButton = QtWidgets.QPushButton(self.Temp_Label)
        self.LowButton.setObjectName("LowButton")
        self.verticalLayout_10.addWidget(self.LowButton)
        self.NormalButton = QtWidgets.QPushButton(self.Temp_Label)
        self.NormalButton.setObjectName("NormalButton")
        self.verticalLayout_10.addWidget(self.NormalButton)
        self.HighButton = QtWidgets.QPushButton(self.Temp_Label)
        self.HighButton.setObjectName("HighButton")
        self.verticalLayout_10.addWidget(self.HighButton)
        self.CalculateButton = QtWidgets.QPushButton(self.Temp_Label)
        self.CalculateButton.setObjectName("CalculateButton")
        self.verticalLayout_10.addWidget(self.CalculateButton)
        self.TempDiff_Text = QtWidgets.QGroupBox(self.Temp_Label)
        self.TempDiff_Text.setObjectName("TempDiff_Text")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.TempDiff_Text)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.LowText = QtWidgets.QLabel(self.TempDiff_Text)
        self.LowText.setObjectName("LowText")
        self.verticalLayout_2.addWidget(self.LowText)
        self.HighText = QtWidgets.QLabel(self.TempDiff_Text)
        self.HighText.setObjectName("HighText")
        self.verticalLayout_2.addWidget(self.HighText)
        self.verticalLayout_10.addWidget(self.TempDiff_Text)
        self.verticalLayout_10.setStretch(1, 1)
        self.verticalLayout_10.setStretch(2, 1)
        self.verticalLayout_10.setStretch(3, 1)
        self.verticalLayout_10.setStretch(4, 1)
        self.verticalLayout_8.addWidget(self.Temp_Label)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.Menu_Label)
        self.File_Label = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.File_Label.setFont(font)
        self.File_Label.setObjectName("File_Label")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.File_Label)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ImportButton = QtWidgets.QPushButton(self.File_Label)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.ImportButton.setFont(font)
        self.ImportButton.setObjectName("ImportButton")
        self.verticalLayout_7.addWidget(self.ImportButton)
        self.ExportButton = QtWidgets.QPushButton(self.File_Label)
        self.ExportButton.setObjectName("ExportButton")
        self.verticalLayout_7.addWidget(self.ExportButton)
        self.OpenButton = QtWidgets.QPushButton(self.File_Label)
        self.OpenButton.setObjectName("OpenButton")
        self.verticalLayout_7.addWidget(self.OpenButton)
        self.SaveButton = QtWidgets.QPushButton(self.File_Label)
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_7.addWidget(self.SaveButton)
        self.ApplyButton = QtWidgets.QPushButton(self.File_Label)
        self.ApplyButton.setObjectName("ApplyButton")
        self.verticalLayout_7.addWidget(self.ApplyButton)
        self.FileName_label = QtWidgets.QLabel(self.File_Label)
        self.FileName_label.setAutoFillBackground(True)
        self.FileName_label.setMidLineWidth(5)
        self.FileName_label.setText("")
        self.FileName_label.setWordWrap(True)
        self.FileName_label.setObjectName("FileName_label")
        self.verticalLayout_7.addWidget(self.FileName_label)
        self.verticalLayout_7.setStretch(0, 2)
        self.verticalLayout_7.setStretch(1, 2)
        self.verticalLayout_7.setStretch(4, 2)
        self.verticalLayout_7.setStretch(5, 1)
        self.verticalLayout_3.addWidget(self.File_Label)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_3.setStretch(1, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 551, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CalculateS2P"))
        self.RL_Label.setTitle(_translate("MainWindow", "回波损耗"))
        self.MaxIL_Label.setTitle(_translate("MainWindow", "边频损耗"))
        self.Ripple_Label.setTitle(_translate("MainWindow", "通带纹波"))
        self.AvgIL_Label.setTitle(_translate("MainWindow", "平均损耗"))
        self.Att_Label.setTitle(_translate("MainWindow", "带外抑制"))
        self.Menu_Label.setTitle(_translate("MainWindow", "Menu"))
        self.Marker_Label.setTitle(_translate("MainWindow", "Marker"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.DeleteButton.setText(_translate("MainWindow", "Delete"))
        self.HelpButton.setText(_translate("MainWindow", "Help"))
        self.Temp_Label.setTitle(_translate("MainWindow", "TempDiff"))
        self.ValueLabel.setTitle(_translate("MainWindow", "测试值/dB"))
        self.ValueEdit.setText(_translate("MainWindow", "18"))
        self.LowButton.setText(_translate("MainWindow", "Low"))
        self.NormalButton.setText(_translate("MainWindow", "Normal"))
        self.HighButton.setText(_translate("MainWindow", "High"))
        self.CalculateButton.setText(_translate("MainWindow", "Calculate"))
        self.TempDiff_Text.setTitle(_translate("MainWindow", "温漂"))
        self.LowText.setText(_translate("MainWindow", "低温：0.0MHz"))
        self.HighText.setText(_translate("MainWindow", "高温：0.0MHz"))
        self.File_Label.setTitle(_translate("MainWindow", "File"))
        self.ImportButton.setText(_translate("MainWindow", "Import"))
        self.ExportButton.setText(_translate("MainWindow", "Export"))
        self.OpenButton.setText(_translate("MainWindow", "Open"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.ApplyButton.setText(_translate("MainWindow", "Apply"))
